services:
  app:
    build: 
      context: .
      target: prod
    image: ${IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}
    stdin_open: true
    tty: true
    volumes:
      - .:/src

  app-debug:
    extends: app
    build: 
      target: debug
    ports:
      - "9229:9229"  # Debugging port
    profiles: [debug]